### ISSUE TITLE
Ran ./errata2cv.py --cv RHEL7_CV got an error.

### ISSUE THREAD

**Issue by dburrell505** [soukron/errata2cv#3]
[root@sattxsawh10 errata2cv]# ./errata2cv.py --cv RHEL7_CV
2018-02-08 17:06:59,400 INFO: Processing content-view RHEL7_CV.
Traceback (most recent call last):
  File "./errata2cv.py", line 262, in <module>
    main()
  File "./errata2cv.py", line 152, in main
    from_date = datetime.strptime(last_published, "%Y-%m-%d  %X %Z").strftime('%Y/%m/%d')
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2018-02-08 12:43:51 -0600' does not match format '%Y-%m-%d  %X %Z'

**Comment by soukron** [comment]
Hi @dburrell505, thanks for reporting the error. Can you provide the version of Satellite 6 which is being used for this issue? I tested it with Satellite 6.2.10 and something may have change in the format reported in the CV information.

**Comment by dburrell505** [comment]
```
[root@sattxsawh10 errata2cv]# rpm -qa satellite
satellite-6.2.14-4.0.el7sat.noarch
```

**Comment by soukron** [comment]
I should have figured out :) I'll need some time to make my own tests. Please stay tuned.

**Comment by soukron** [comment]
Hi @dburrell505, please update your code with the latest master branch.

Also, please, as the latest update doesn't address this specific error I'll need more information to reproduce the error as it works in my environment.

Please:
- make sure you have at least one published version of your content view
- run the command with --debug parameter and attach the log.

**Comment by dburrell505** [comment]
Here are the results of the command as requested with the same error:

```
[root@sattxsawh10 errata2cv]# ./errata2cv.py --cv RHEL7_CV --dry-run --debug
2018-03-19 15:31:58,838 DEBUG: Looking for organization information.
2018-03-19 15:31:58,838 DEBUG: Request: GET https://sattxsawh10.MYORG.com/katello/api/organizations/MYORG
2018-03-19 15:31:59,144 DEBUG: Request result: {"library_id": 1, "hostgroups": [{"title": "RHEL6_NP_HG", "id": 2, "name": "RHEL6_NP_HG"}, {"title": "RHEL6_NP_PUPPET_HG", "id": 6, "name": "RHEL6_NP_PUPPET_HG"}, {"title": "RHEL6_P_HG", "id": 9, "name": "RHEL6_P_HG"}, {"title": "RHEL7_DMZ_HG", "id": 5, "name": "RHEL7_DMZ_HG"}, {"title": "RHEL7_DMZ_PUPPET_HG", "id": 7, "name": "RHEL7_DMZ_PUPPET_HG"}, {"title": "RHEL7_NP_HG", "id": 1, "name": "RHEL7_NP_HG"}, {"title": "RHEL7_NP_PUPPET_HG", "id": 8, "name": "RHEL7_NP_PUPPET_HG"}, {"title": "RHEL7_P_HG", "id": 10, "name": "RHEL7_P_HG"}, {"title": "RHEL7_P_PUPPET_HG", "id": 11, "name": "RHEL7_P_PUPPET_HG"}], "updated_at": "2018-02-14 18:26:20 -0600", "environments": [{"name": "example_env", "id": 7}, {"name": "KT_MYORG_Library_A_PUPPET_CCV_18", "id": 6}, {"name": "KT_MYORG_Library_PUPPET_FORGE_CV_11", "id": 5}, {"name": "KT_MYORG_Library_MYORG_CV_21", "id": 8}, {"name": "KT_MYORG_Library_MYORG_PUPPET_16", "id": 4}, {"name": "NON_PROD", "id": 2}, {"name": "PROD", "id": 1}], "ptables": [{"id": 61, "created_at": "2018-01-29 13:44:20 -0600", "os_family": "Redhat", "updated_at": "2018-01-29 13:44:20 -0600", "name": "Kickstart default"}, {"id": 104, "created_at": "2018-01-31 11:23:58 -0600", "os_family": "Redhat", "updated_at": "2018-01-31 11:25:58 -0600", "name": "MYORG RHEL6 Standard Partition Table"}, {"id": 103, "created_at": "2018-01-31 11:20:53 -0600", "os_family": "Redhat", "updated_at": "2018-01-31 11:26:00 -0600", "name": "MYORG RHEL7 Standard Partition Table"}], "provisioning_templates": [{"template_kind_name": "provision", "template_kind_id": 5, "id": 10, "name": "Atomic Kickstart default"}, {"template_kind_name": "Bootdisk", "template_kind_id": 1, "id": 72, "name": "Boot disk iPXE - generic host"}, {"template_kind_name": "Bootdisk", "template_kind_id": 1, "id": 71, "name": "Boot disk iPXE - host"}, {"template_kind_name": "kexec", "template_kind_id": 11, "id": 82, "name": "Discovery Red Hat kexec"}, {"template_kind_name": null, "template_kind_id": null, "id": 45, "name": "fix_hosts"}, {"template_kind_name": null, "template_kind_id": null, "id": 46, "name": "freeipa_register"}, {"template_kind_name": null, "template_kind_id": null, "id": 47, "name": "http_proxy"}, {"template_kind_name": null, "template_kind_id": null, "id": 76, "name": "idm_register"}, {"template_kind_name": "finish", "template_kind_id": 6, "id": 26, "name": "Kickstart default finish"}, {"template_kind_name": "iPXE", "template_kind_id": 4, "id": 28, "name": "Kickstart default iPXE"}, {"template_kind_name": "PXELinux", "template_kind_id": 2, "id": 27, "name": "Kickstart default PXELinux"}, {"template_kind_name": "user_data", "template_kind_id": 8, "id": 29, "name": "Kickstart default user data"}, {"template_kind_name": null, "template_kind_id": null, "id": 48, "name": "kickstart_networking_setup"}, {"template_kind_name": null, "template_kind_id": null, "id": 50, "name": "puppet.conf"}, {"template_kind_name": "PXEGrub", "template_kind_id": 3, "id": 4, "name": "PXEGrub default local boot"}, {"template_kind_name": "PXELinux", "template_kind_id": 2, "id": 5, "name": "PXELinux chain iPXE"}, {"template_kind_name": "PXELinux", "template_kind_id": 2, "id": 6, "name": "PXELinux chain iPXE UNDI"}, {"template_kind_name": "PXELinux", "template_kind_id": 2, "id": 2, "name": "PXELinux default local boot"}, {"template_kind_name": "PXELinux", "template_kind_id": 2, "id": 3, "name": "PXELinux default memdisk"}, {"template_kind_name": "PXELinux", "template_kind_id": 2, "id": 1, "name": "PXELinux global default"}, {"template_kind_name": null, "template_kind_id": null, "id": 51, "name": "redhat_register"}, {"template_kind_name": null, "template_kind_id": null, "id": 52, "name": "remote_execution_ssh_keys"}, {"template_kind_name": "provision", "template_kind_id": 5, "id": 77, "name": "Satellite Atomic Kickstart Default"}, {"template_kind_name": "provision", "template_kind_id": 5, "id": 73, "name": "Satellite Kickstart Default"}, {"template_kind_name": "finish", "template_kind_id": 6, "id": 75, "name": "Satellite Kickstart Default Finish"}, {"template_kind_name": "user_data", "template_kind_id": 8, "id": 74, "name": "Satellite Kickstart Default User Data"}, {"template_kind_name": null, "template_kind_id": null, "id": 69, "name": "subscription_manager_registration"}, {"template_kind_name": "user_data", "template_kind_id": 8, "id": 35, "name": "UserData default"}, {"template_kind_name": null, "template_kind_id": null, "id": 107, "name": "MYORG Firewall Services"}, {"template_kind_name": "provision", "template_kind_id": 5, "id": 105, "name": "MYORG Satellite Kickstart"}, {"template_kind_name": null, "template_kind_id": null, "id": 106, "name": "MYORG Software Packages"}], "service_levels": ["Premium", "Standard"], "compute_resources": [], "id": 1, "description": "", "parent_name": null, "parameters": [], "owner_details": {"updated": "2018-02-28T20:37:56.912+0000", "displayName": "MYORG", "parentOwner": null, "created": "2018-01-29T19:44:21.268+0000", "logLevel": null, "contentPrefix": "/MYORG/$env", "virt_who": true, "href": "/owners/MYORG", "defaultServiceLevel": null, "key": "MYORG", "autobindDisabled": null, "upstreamConsumer": {"updated": "2018-02-28T20:37:56.564+0000", "name": "MYORG", "created": "2018-02-28T20:37:56.564+0000", "webUrl": "access.redhat.com/management/distributors/", "uuid": "UUID", "apiUrl": "https://subscription.rhn.redhat.com/subscription/consumers/", "ownerId": "OWNERID", "type": {"manifest": true, "id": "1006", "label": "sam"}, "id": "ID", "idCert": {"updated": "2018-02-28T20:37:56.562+0000", "created": "2018-02-28T20:37:56.562+0000", "cert": "----- CERTIFICATE-----\n", "key": "-----RSA PRIVATE KEY-----\n", "serial": {"updated": "2018-02-28T20:37:56.558+0000", "revoked": false, "created": "2018-02-28T20:37:56.558+0000", "expiration": "2019-01-29T19:30:56.000+0000", "collected": false, "serial": 741624685702919184, "id": ID}, "id": "ID"}}, "id": "OWNERID"}, "media": [{"id": 10, "name": "MYORG/Library/Red_Hat_Server/Red_Hat_Enterprise_Linux_6_Server_Kickstart_x86_64_6_9"}, {"id": 13, "name": "MYORG/Library/Red_Hat_Server/Red_Hat_Enterprise_Linux_7_Server_Kickstart_x86_64_7_3"}, {"id": 9, "name": "MYORG/Library/Red_Hat_Server/Red_Hat_Enterprise_Linux_7_Server_Kickstart_x86_64_7_4"}, {"id": 11, "name": "MYORG/Library/Red_Hat_Workstation/Red_Hat_Enterprise_Linux_6_Workstation_Kickstart_x86_64_6_9"}, {"id": 12, "name": "MYORG/Library/Red_Hat_Workstation/Red_Hat_Enterprise_Linux_7_Workstation_Kickstart_x86_64_7_4"}], "label": "MYORG", "parent_id": null, "redhat_repository_url": "https://cdn.redhat.com", "select_all_types": ["Domain"], "subnets": [{"network_address": "10.200.130.0/24", "id": 149, "name": "10.200.130.0"}, {"network_address": "192.168.35.0/24", "id": 11, "name": "192.168.35.0"}, {"network_address": "192.168.62.0/24", "id": 12, "name": "192.168.62.0"}, {"network_address": "192.168.65.0/24", "id": 13, "name": "192.168.65.0"}, {"network_address": "192.168.66.0/24", "id": 14, "name": "192.168.66.0"}, {"network_address": "192.168.67.0/24", "id": 15, "name": "192.168.67.0"}, {"network_address": "192.168.68.0/24", "id": 16, "name": "192.168.68.0"}, {"network_address": "192.168.69.0/24", "id": 17, "name": "192.168.69.0"}, {"network_address": "10.214.145.0/24", "id": 5, "name": "10.214.145.0"}, {"network_address": "10.214.127.0/24", "id": 9, "name": "10.214.127.0"}, {"network_address": "10.214.126.0/24", "id": 10, "name": "10.214.126.0"}, {"network_address": "192.168.70.0/24", "id": 18, "name": "192.168.70.0"}, {"network_address": "192.168.71.0/24", "id": 19, "name": "192.168.71.0"}, {"network_address": "192.168.72.0/24", "id": 20, "name": "192.168.72.0"}, {"network_address": "192.168.73.0/24", "id": 21, "name": "192.168.73.0"}, {"network_address": "192.168.74.0/24", "id": 22, "name": "192.168.74.0"}, {"network_address": "192.168.75.0/24", "id": 23, "name": "192.168.75.0"}, {"network_address": "192.168.76.0/24", "id": 24, "name": "192.168.76.0"}, {"network_address": "192.168.77.0/24", "id": 25, "name": "192.168.77.0"}, {"network_address": "192.168.78.0/24", "id": 26, "name": "192.168.78.0"}, {"network_address": "192.168.79.0/24", "id": 27, "name": "192.168.79.0"}, {"network_address": "192.168.80.0/24", "id": 28, "name": "192.168.80.0"}, {"network_address": "10.212.244.0/24", "id": 29, "name": "10.212.244.0"}, {"network_address": "10.212.1.0/24", "id": 30, "name": "10.212.1.0"}, {"network_address": "10.212.2.0/24", "id": 31, "name": "10.212.2.0"}, {"network_address": "10.212.3.0/24", "id": 32, "name": "10.212.3.0"}, {"network_address": "10.212.4.0/24", "id": 33, "name": "10.212.4.0"}, {"network_address": "10.212.5.0/24", "id": 34, "name": "10.212.5.0"}, {"network_address": "10.212.6.0/24", "id": 35, "name": "10.212.6.0"}, {"network_address": "10.212.7.0/24", "id": 36, "name": "10.212.7.0"}, {"network_address": "10.212.8.0/24", "id": 37, "name": "10.212.8.0"}, {"network_address": "10.212.9.0/24", "id": 38, "name": "10.212.9.0"}, {"network_address": "10.212.10.0/24", "id": 39, "name": "10.212.10.0"}, {"network_address": "10.212.11.0/24", "id": 40, "name": "10.212.11.0"}, {"network_address": "10.212.12.0/24", "id": 41, "name": "10.212.12.0"}, {"network_address": "10.212.13.0/24", "id": 42, "name": "10.212.13.0"}, {"network_address": "10.212.14.0/24", "id": 43, "name": "10.212.14.0"}, {"network_address": "10.212.47.0/24", "id": 44, "name": "10.212.47.0"}, {"network_address": "10.212.50.0/24", "id": 45, "name": "10.212.50.0"}, {"network_address": "10.212.51.0/24", "id": 46, "name": "10.212.51.0"}, {"network_address": "10.212.52.0/24", "id": 47, "name": "10.212.52.0"}, {"network_address": "10.212.53.0/24", "id": 48, "name": "10.212.53.0"}, {"network_address": "10.212.54.0/24", "id": 49, "name": "10.212.54.0"}, {"network_address": "10.212.55.0/24", "id": 50, "name": "10.212.55.0"}, {"network_address": "10.212.102.0/24", "id": 51, "name": "10.212.102.0"}, {"network_address": "10.212.104.0/24", "id": 52, "name": "10.212.104.0"}, {"network_address": "10.212.191.0/24", "id": 53, "name": "10.212.191.0"}, {"network_address": "10.212.192.0/24", "id": 54, "name": "10.212.192.0"}, {"network_address": "10.212.193.0/24", "id": 55, "name": "10.212.193.0"}, {"network_address": "10.212.194.0/24", "id": 56, "name": "10.212.194.0"}, {"network_address": "10.212.195.0/24", "id": 57, "name": "10.212.195.0"}, {"network_address": "10.212.197.0/24", "id": 58, "name": "10.212.197.0"}, {"network_address": "10.212.200.0/24", "id": 59, "name": "10.212.200.0"}, {"network_address": "10.212.201.0/24", "id": 60, "name": "10.212.201.0"}, {"network_address": "10.212.203.0/24", "id": 61, "name": "10.212.203.0"}, {"network_address": "10.212.204.0/24", "id": 62, "name": "10.212.204.0"}, {"network_address": "10.212.205.0/24", "id": 63, "name": "10.212.205.0"}, {"network_address": "10.212.206.0/24", "id": 64, "name": "10.212.206.0"}, {"network_address": "10.212.207.0/24", "id": 65, "name": "10.212.207.0"}, {"network_address": "10.212.208.0/24", "id": 66, "name": "10.212.208.0"}, {"network_address": "10.212.209.0/24", "id": 67, "name": "10.212.209.0"}, {"network_address": "10.212.210.0/24", "id": 68, "name": "10.212.210.0"}, {"network_address": "10.212.211.0/24", "id": 69, "name": "10.212.211.0"}, {"network_address": "10.212.212.0/24", "id": 70, "name": "10.212.212.0"}, {"network_address": "10.212.213.0/24", "id": 71, "name": "10.212.213.0"}, {"network_address": "10.212.214.0/24", "id": 72, "name": "10.212.214.0"}, {"network_address": "10.212.220.0/24", "id": 73, "name": "10.212.220.0"}, {"network_address": "10.212.221.0/24", "id": 74, "name": "10.212.221.0"}, {"network_address": "10.212.222.0/24", "id": 75, "name": "10.212.222.0"}, {"network_address": "10.212.223.0/24", "id": 76, "name": "10.212.223.0"}, {"network_address": "10.212.224.0/24", "id": 77, "name": "10.212.224.0"}, {"network_address": "10.212.225.0/24", "id": 78, "name": "10.212.225.0"}, {"network_address": "10.212.226.0/24", "id": 79, "name": "10.212.226.0"}, {"network_address": "10.212.227.0/24", "id": 80, "name": "10.212.227.0"}, {"network_address": "10.212.228.0/24", "id": 81, "name": "10.212.228.0"}, {"network_address": "10.212.229.0/24", "id": 82, "name": "10.212.229.0"}, {"network_address": "10.212.230.0/24", "id": 83, "name": "10.212.230.0"}, {"network_address": "10.212.231.0/24", "id": 84, "name": "10.212.231.0"}, {"network_address": "10.212.232.0/24", "id": 85, "name": "10.212.232.0"}, {"network_address": "10.212.233.0/24", "id": 86, "name": "10.212.233.0"}, {"network_address": "10.212.234.0/24", "id": 87, "name": "10.212.234.0"}, {"network_address": "10.212.235.0/24", "id": 88, "name": "10.212.235.0"}, {"network_address": "10.212.236.0/24", "id": 89, "name": "10.212.236.0"}, {"network_address": "10.212.237.0/24", "id": 90, "name": "10.212.237.0"}, {"network_address": "10.212.238.0/24", "id": 91, "name": "10.212.238.0"}, {"network_address": "10.212.239.0/24", "id": 92, "name": "10.212.239.0"}, {"network_address": "10.212.242.0/24", "id": 93, "name": "10.212.242.0"}, {"network_address": "10.212.251.0/24", "id": 94, "name": "10.212.251.0"}, {"network_address": "10.212.252.0/24", "id": 95, "name": "10.212.252.0"}, {"network_address": "10.214.2.0/24", "id": 96, "name": "10.214.2.0"}, {"network_address": "10.214.10.0/24", "id": 97, "name": "10.214.10.0"}, {"network_address": "10.214.17.0/24", "id": 98, "name": "10.214.17.0"}, {"network_address": "10.214.18.0/24", "id": 99, "name": "10.214.18.0"}, {"network_address": "10.214.19.0/24", "id": 100, "name": "10.214.19.0"}, {"network_address": "10.214.180.0/24", "id": 101, "name": "10.214.180.0"}, {"network_address": "10.214.181.0/24", "id": 102, "name": "10.214.181.0"}, {"network_address": "10.214.182.0/24", "id": 103, "name": "10.214.182.0"}, {"network_address": "10.214.183.0/24", "id": 104, "name": "10.214.183.0"}, {"network_address": "10.214.184.0/24", "id": 105, "name": "10.214.184.0"}, {"network_address": "10.214.185.0/24", "id": 106, "name": "10.214.185.0"}, {"network_address": "10.214.186.0/24", "id": 107, "name": "10.214.186.0"}, {"network_address": "10.214.187.0/24", "id": 108, "name": "10.214.187.0"}, {"network_address": "10.214.188.0/24", "id": 109, "name": "10.214.188.0"}, {"network_address": "10.214.189.0/24", "id": 110, "name": "10.214.189.0"}, {"network_address": "10.214.190.0/24", "id": 111, "name": "10.214.190.0"}, {"network_address": "10.214.191.0/24", "id": 112, "name": "10.214.191.0"}, {"network_address": "10.214.192.0/24", "id": 113, "name": "10.214.192.0"}, {"network_address": "10.214.193.0/24", "id": 114, "name": "10.214.193.0"}, {"network_address": "10.214.194.0/24", "id": 115, "name": "10.214.194.0"}, {"network_address": "10.214.195.0/24", "id": 116, "name": "10.214.195.0"}, {"network_address": "10.214.196.0/24", "id": 117, "name": "10.214.196.0"}, {"network_address": "10.214.197.0/24", "id": 118, "name": "10.214.197.0"}, {"network_address": "10.214.198.0/24", "id": 119, "name": "10.214.198.0"}, {"network_address": "10.214.199.0/24", "id": 120, "name": "10.214.199.0"}, {"network_address": "10.214.200.0/24", "id": 121, "name": "10.214.200.0"}, {"network_address": "10.214.201.0/24", "id": 122, "name": "10.214.201.0"}, {"network_address": "10.214.202.0/24", "id": 123, "name": "10.214.202.0"}, {"network_address": "10.214.231.0/24", "id": 124, "name": "10.214.231.0"}, {"network_address": "10.214.232.0/24", "id": 125, "name": "10.214.232.0"}, {"network_address": "10.214.233.0/24", "id": 126, "name": "10.214.233.0"}, {"network_address": "10.214.234.0/24", "id": 127, "name": "10.214.234.0"}, {"network_address": "10.214.235.0/24", "id": 128, "name": "10.214.235.0"}, {"network_address": "10.214.236.0/24", "id": 129, "name": "10.214.236.0"}, {"network_address": "10.214.237.0/24", "id": 130, "name": "10.214.237.0"}, {"network_address": "10.214.238.0/24", "id": 131, "name": "10.214.238.0"}, {"network_address": "10.214.239.0/24", "id": 132, "name": "10.214.239.0"}, {"network_address": "10.214.204.0/24", "id": 133, "name": "10.214.204.0"}, {"network_address": "10.214.205.0/24", "id": 134, "name": "10.214.205.0"}, {"network_address": "10.214.135.0/24", "id": 1, "name": "10.214.135.0"}, {"network_address": "10.214.207.0/24", "id": 136, "name": "10.214.207.0"}, {"network_address": "10.214.110.0/24", "id": 137, "name": "10.214.110.0"}, {"network_address": "10.214.111.0/24", "id": 138, "name": "10.214.111.0"}, {"network_address": "10.214.112.0/24", "id": 139, "name": "10.214.112.0"}, {"network_address": "10.214.120.0/24", "id": 140, "name": "10.214.120.0"}, {"network_address": "10.214.121.0/24", "id": 141, "name": "10.214.121.0"}, {"network_address": "10.214.122.0/24", "id": 142, "name": "10.214.122.0"}, {"network_address": "10.214.130.0/24", "id": 143, "name": "10.214.130.0"}, {"network_address": "10.214.140.0/24", "id": 144, "name": "10.214.140.0"}, {"network_address": "10.214.115.0/24", "id": 145, "name": "10.214.115.0"}, {"network_address": "10.214.116.0/24", "id": 146, "name": "10.214.116.0"}, {"network_address": "10.214.117.0/24", "id": 147, "name": "10.214.117.0"}, {"network_address": "10.214.125.0/24", "id": 148, "name": "10.214.125.0"}, {"network_address": "10.214.206.0/24", "id": 135, "name": "10.214.206.0"}], "service_level": null, "users": [{"login": "dburrell505", "id": 4}, {"login": "USER1", "id": 24}, {"login": "USER2", "id": 27}, {"login": "USER4", "id": 25}, {"login": "USER5", "id": 31}, {"login": "VIEWER1", "id": 26}, {"login": "USER3", "id": 32}], "locations": [{"description": "", "title": "DC2", "id": 2, "name": "DC2"}, {"description": "", "title": "DC2", "id": 2, "name": "DC2"}, {"description": "Data Center 1", "title": "DC1", "id": 3, "name": "DC1"}], "config_templates": [{"template_kind_name": "provision", "template_kind_id": 5, "id": 10, "name": "Atomic Kickstart default"}, {"template_kind_name": "Bootdisk", "template_kind_id": 1, "id": 72, "name": "Boot disk iPXE - generic host"}, {"template_kind_name": "Bootdisk", "template_kind_id": 1, "id": 71, "name": "Boot disk iPXE - host"}, {"template_kind_name": "kexec", "template_kind_id": 11, "id": 82, "name": "Discovery Red Hat kexec"}, {"template_kind_name": null, "template_kind_id": null, "id": 45, "name": "fix_hosts"}, {"template_kind_name": null, "template_kind_id": null, "id": 46, "name": "freeipa_register"}, {"template_kind_name": null, "template_kind_id": null, "id": 47, "name": "http_proxy"}, {"template_kind_name": null, "template_kind_id": null, "id": 76, "name": "idm_register"}, {"template_kind_name": "finish", "template_kind_id": 6, "id": 26, "name": "Kickstart default finish"}, {"template_kind_name": "iPXE", "template_kind_id": 4, "id": 28, "name": "Kickstart default iPXE"}, {"template_kind_name": "PXELinux", "template_kind_id": 2, "id": 27, "name": "Kickstart default PXELinux"}, {"template_kind_name": "user_data", "template_kind_id": 8, "id": 29, "name": "Kickstart default user data"}, {"template_kind_name": null, "template_kind_id": null, "id": 48, "name": "kickstart_networking_setup"}, {"template_kind_name": null, "template_kind_id": null, "id": 50, "name": "puppet.conf"}, {"template_kind_name": "PXEGrub", "template_kind_id": 3, "id": 4, "name": "PXEGrub default local boot"}, {"template_kind_name": "PXELinux", "template_kind_id": 2, "id": 5, "name": "PXELinux chain iPXE"}, {"template_kind_name": "PXELinux", "template_kind_id": 2, "id": 6, "name": "PXELinux chain iPXE UNDI"}, {"template_kind_name": "PXELinux", "template_kind_id": 2, "id": 2, "name": "PXELinux default local boot"}, {"template_kind_name": "PXELinux", "template_kind_id": 2, "id": 3, "name": "PXELinux default memdisk"}, {"template_kind_name": "PXELinux", "template_kind_id": 2, "id": 1, "name": "PXELinux global default"}, {"template_kind_name": null, "template_kind_id": null, "id": 51, "name": "redhat_register"}, {"template_kind_name": null, "template_kind_id": null, "id": 52, "name": "remote_execution_ssh_keys"}, {"template_kind_name": "provision", "template_kind_id": 5, "id": 77, "name": "Satellite Atomic Kickstart Default"}, {"template_kind_name": "provision", "template_kind_id": 5, "id": 73, "name": "Satellite Kickstart Default"}, {"template_kind_name": "finish", "template_kind_id": 6, "id": 75, "name": "Satellite Kickstart Default Finish"}, {"template_kind_name": "user_data", "template_kind_id": 8, "id": 74, "name": "Satellite Kickstart Default User Data"}, {"template_kind_name": null, "template_kind_id": null, "id": 69, "name": "subscription_manager_registration"}, {"template_kind_name": "user_data", "template_kind_id": 8, "id": 35, "name": "UserData default"}, {"template_kind_name": null, "template_kind_id": null, "id": 107, "name": "MYORG Firewall Services"}, {"template_kind_name": "provision", "template_kind_id": 5, "id": 105, "name": "MYORG Satellite Kickstart"}, {"template_kind_name": null, "template_kind_id": null, "id": 106, "name": "MYORG Software Packages"}], "ancestry": null, "realms": [], "default_content_view_id": 1, "name": "MYORG", "smart_proxies": [{"url": "https://sattxsawh10.MYORG.com:9090", "name": "sattxsawh10.MYORG.com", "id": 1}], "created_at": "2018-01-29 13:44:18 -0600", "title": "MYORG", "domains": [{"id": 2, "name": "corp.MYORG.com"}, {"id": 1, "name": "MYORG.com"}]}
2018-03-19 15:31:59,150 INFO: Processing content-view RHEL7_CV.
2018-03-19 15:31:59,150 DEBUG: Request: GET https://sattxsawh10.MYORG.com/katello/api/organizations/1/content_views
2018-03-19 15:31:59,150 DEBUG: Request data: {"search": "name=RHEL7_CV", "nondefault": 1, "noncomposite": 1}
2018-03-19 15:31:59,229 DEBUG: Request result: {"sort": {"by": null, "order": null}, "search": "name=RHEL7_CV", "results": [{"last_published": "2018-02-13 14:58:02 -0600", "name": "RHEL7_CV", "versions": [{"version": "1.0", "environment_ids": [], "id": 2, "published": "2018-01-30 12:44:00 -0600"}, {"version": "2.0", "environment_ids": [], "id": 121, "published": "2018-02-14 18:08:25 -0600"}, {"version": "3.0", "environment_ids": [], "id": 137, "published": "2018-02-28 02:00:06 -0600"}, {"version": "3.1", "environment_ids": [], "id": 153, "published": "2018-03-10 22:11:08 -0600"}, {"version": "3.2", "environment_ids": [1], "id": 155, "published": "2018-03-19 14:49:39 -0500"}, {"version": "1.1", "environment_ids": [], "id": 98, "published": "2018-02-13 14:58:02 -0600"}], "composite": false, "created_at": "2018-01-30 10:01:44 -0600", "repositories": [{"label": "Red_Hat_Enterprise_Linux_7_Server_RPMs_x86_64_7Server", "id": 1, "content_type": "yum", "name": "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"}, {"label": "Red_Hat_Enterprise_Linux_7_Server_-_Extras_RPMs_x86_64", "id": 2, "content_type": "yum", "name": "Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64"}, {"label": "Red_Hat_Enterprise_Linux_7_Server_-_Optional_RPMs_x86_64_7Server", "id": 3, "content_type": "yum", "name": "Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server"}, {"label": "Red_Hat_Enterprise_Linux_7_Server_-_Supplementary_RPMs_x86_64_7Server", "id": 4, "content_type": "yum", "name": "Red Hat Enterprise Linux 7 Server - Supplementary RPMs x86_64 7Server"}, {"label": "Red_Hat_Software_Collections_RPMs_for_Red_Hat_Enterprise_Linux_7_Server_x86_64_7Server", "id": 30, "content_type": "yum", "name": "Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server x86_64 7Server"}, {"label": "Red_Hat_Satellite_Tools_6_2_for_RHEL_7_Server_RPMs_x86_64", "id": 5, "content_type": "yum", "name": "Red Hat Satellite Tools 6.2 for RHEL 7 Server RPMs x86_64"}], "updated_at": "2018-02-28 02:00:06 -0600", "environments": [{"permissions": {"readable": true}, "label": "Library", "id": 1, "name": "Library"}], "label": "RHEL7_CV", "default": false, "component_ids": [], "components": [], "organization": {"id": 1, "name": "MYORG", "label": "MYORG"}, "activation_keys": [], "repository_ids": [1, 2, 3, 4, 30, 5], "puppet_modules": [], "permissions": {"promote_or_remove_content_views": true, "view_content_views": true, "publish_content_views": true, "destroy_content_views": true, "edit_content_views": true}, "id": 2, "next_version": 4, "description": null}], "error": null, "per_page": 200, "total": 14, "subtotal": 1, "page": 1}
Traceback (most recent call last):
  File "./errata2cv.py", line 279, in <module>
    main()
  File "./errata2cv.py", line 168, in main
    from_date = datetime.strptime(last_published, "%Y-%m-%d  %X %Z").strftime('%Y/%m/%d')
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2018-02-13 14:58:02 -0600' does not match format '%Y-%m-%d  %X %Z'
```

**Comment by soukron** [comment]
Thanks for the log. I see the difference in the date format. I'll take a look.
