### ISSUE TITLE
try to publish bugfix that in the errata view as bugs by this date but program didn't do anything.

### ISSUE THREAD

**Issue by dburrell505** [soukron/errata2cv#5]
[root@sattxsawh10 errata2cv]# ./errata2cv.py --cv RHEL7_CV --type bugfix --propagate --from-date 2018/02/05 --update-hosts NON_PROD
2018-02-08 16:57:23,541 INFO: Processing content-view RHEL7_CV.
2018-02-08 16:57:23,633 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server
2018-02-08 16:57:23,750 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64
2018-02-08 16:57:23,844 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server
2018-02-08 16:57:23,954 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Supplementary RPMs x86_64 7Server
2018-02-08 16:57:24,035 INFO: Searching for erratas in repository Red Hat Satellite Tools 6.2 for RHEL 7 Server RPMs x86_64
2018-02-08 16:57:24,115 INFO: Searching for erratas in repository Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server x86_64 7Server
2018-02-08 16:57:24,203 INFO: No new existing erratas for RHEL7_CV CV.

**Comment by soukron** [comment]
Hi @dburrell505, thanks for reporting the error. Can you provide the version of Satellite 6 which is being used for this issue? 

In the other hand, can you double check in Satellite UI if there are erratas (bugfixes considered Critical) in the repositories? Critical is the default severity to include and I don't see in your command line execution any modifier to it so maybe it's true that there aren't new erratas for your CV.

**Comment by dburrell505** [comment]
We ran the code with all of the options and this is what we got for both bugfixes and security types and the output is below.

We checked the tasks and the content views and nothing was happening.

```
[root@sattxsawh10 errata2cv]# ./errata2cv.py --cv RHEL7_CV --type bugfix --propagate --from-date 2018/02/09 --update-hosts NON_PROD --severity none,low,moderate,important,critical
2018-02-09 09:22:40,405 INFO: Processing content-view RHEL7_CV.
2018-02-09 09:22:40,626 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server
2018-02-09 09:22:40,782 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64
2018-02-09 09:22:40,878 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server
2018-02-09 09:22:41,057 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Supplementary RPMs x86_64 7Server
2018-02-09 09:22:41,144 INFO: Searching for erratas in repository Red Hat Satellite Tools 6.2 for RHEL 7 Server RPMs x86_64
2018-02-09 09:22:41,229 INFO: Searching for erratas in repository Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server x86_64 7Server
2018-02-09 09:22:41,322 INFO: No new existing erratas for RHEL7_CV CV.
```

```
[root@sattxsawh10 errata2cv]# ./errata2cv.py --cv RHEL7_CV --type security --propagate --from-date 2018/02/09 --update-hosts NON_PROD --severity none,low,moderate,important,critical
2018-02-09 09:23:59,993 INFO: Processing content-view RHEL7_CV.
2018-02-09 09:24:00,087 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server
2018-02-09 09:24:00,227 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64
2018-02-09 09:24:00,330 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server
2018-02-09 09:24:00,461 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Supplementary RPMs x86_64 7Server
2018-02-09 09:24:00,560 INFO: Searching for erratas in repository Red Hat Satellite Tools 6.2 for RHEL 7 Server RPMs x86_64
2018-02-09 09:24:00,650 INFO: Searching for erratas in repository Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server x86_64 7Server
2018-02-09 09:24:00,739 INFO: No new existing erratas for RHEL7_CV CV.
```

**Comment by soukron** [comment]
Bear in mind that you are asking errata2cv to add to your CV any new errata existing in your synced repositories which has been published FROM today.

According to Red Hat errata information [1], no new erratas for RHEL 7 have been published since 05 Feb 2018 so your results sound good to me: errata2cv can't add any errata published from today as there aren't new erratas published matching your criteria.

[1] https://access.redhat.com/errata/#/?q=&p=1&sort=portal_publication_date%20desc&rows=10&documentKind=Errata&portal_product=Red%20Hat%20Enterprise%20Linux&portal_product_variant=Red%20Hat%20Enterprise%20Linux%20Server&portal_product_version=7

**Comment by soukron** [comment]
Also, considering your recent Satellite version (6.2.14), your CV will likely have all the erratas if you created yesterday or in the last week so you may have to wait for a few days more to have erratas available for you. Are you also syncing your repositories in a daily basis?

**Comment by dburrell505** [comment]
We installed 6.2.12-4 about 9 days ago and updated to 6.2.14 two days ago.  And yes, we are syncing daily.

We have plenty of errata since nine days ago.

**Comment by soukron** [comment]
I understand but then do not restrict **--from-date** to today and use the day where the erratas where published instead. As said, there are no erratas published today so your previous executions are fine. The latter erratas were published on Feb 5th so try with Feb 1st as date instead of today.

What about running this command instead?
`
./errata2cv.py --cv RHEL7_CV --type security --propagate --from-date 2018/02/01 --update-hosts NON_PROD --severity none,low,moderate,important,critical --dry-run
`

**Comment by dburrell505** [comment]
We tried to run it from the template and it's asking for a date but the template doesn't have date fields, so we thought they were implied.  Here is the output:

```
2018-02-09 11:39:18,108 INFO: Processing content-view RHEL6_CV.
Traceback (most recent call last):
  File "/opt/errata2cv/errata2cv.py", line 262, in <module>
    main()
  File "/opt/errata2cv/errata2cv.py", line 152, in main
    from_date = datetime.strptime(last_published, "%Y-%m-%d  %X %Z").strftime('%Y/%m/%d')
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2018-02-09 10:08:04 -0600' does not match format '%Y-%m-%d  %X %Z'
Exit status: 1
```

the template sent:

```
/opt/errata2cv/errata2cv.py --cv RHEL6_CV --type bugfix,security,enhacement --severity none,low,moderate,important,critical --propagate --update-hosts NON_PROD 
```

attached a screen shot.

![job-invocation-screen-shot](https://user-images.githubusercontent.com/36283150/36041586-954bffe4-0d8e-11e8-9aa2-06bcef6c5c2a.PNG)

**Comment by soukron** [comment]
Ok, something seems to be wrong with the dates in the API as it now includes zone offset (or it was there but didn't appeared for me). I'll need to check it but for the sake of this issue, please run the command that I sent to you (which includes Feb 1st as date instead of the CV published date) to check if then it has some erratas or not.

**Comment by dburrell505** [comment]
```
[root@sattxsawh10 errata2cv]# ./errata2cv.py --cv RHEL7_CV --type security --propagate --from-date 2018/02/01 --update-hosts NON_PROD --severity none,low,moderate,important,critical --dry-run
2018-02-09 13:16:45,600 INFO: Processing content-view RHEL7_CV.
2018-02-09 13:16:45,691 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server
2018-02-09 13:16:45,824 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64
2018-02-09 13:16:45,910 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server
2018-02-09 13:16:46,030 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Supplementary RPMs x86_64 7Server
2018-02-09 13:16:46,114 INFO: Searching for erratas in repository Red Hat Satellite Tools 6.2 for RHEL 7 Server RPMs x86_64
2018-02-09 13:16:46,204 INFO: Searching for erratas in repository Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server x86_64 7Server
2018-02-09 13:16:46,337 INFO: Found RHSA-2018:0279 (Security - Moderate) errata. Reboot suggested: No.
2018-02-09 13:16:46,337 INFO: Selected content-view RHEL7_CV (version 1.0) as baseline to include 1 erratas.
2018-02-09 13:16:46,337 INFO: Skipping incremental content-view and/or installation in hosts as dry-run was specified.
2018-02-09 13:16:46,338 INFO: Finished processing CV RHEL7_CV.
```

**Comment by soukron** [comment]
That's what I expected: if you go enough back in time, erratas appear. The filter is working fine as long as you provide a (valid) date in the command but it fails if the date is gathered from the CV.

To me this issue isn't a real issue in the code. Is that okay if we close it and continue with the issue in the date in the other issue you've opened?

**Comment by dburrell505** [comment]
Absolutely, please close this issue.
