### ISSUE TITLE
Different ./errata2cv.py --cv RHEL7_CV error

### ISSUE THREAD

**Issue by dburrell505** [soukron/errata2cv#7]
Not sure if this is related to the prior error, but I am seeing the following now:
```
[root@sattxsawh10 errata2cv]# ./errata2cv.py --cv RHEL7_CV --type security --propagate --from-date 2018/02/25 --update-hosts DMZ --severity none,low,moderate,important,critical
2018-03-08 13:53:00,206 INFO: Processing content-view RHEL7_CV.
2018-03-08 13:53:00,286 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server
2018-03-08 13:53:00,456 INFO: Found RHSA-2018:0406 (Security - Moderate) errata. Reboot suggested: No.
2018-03-08 13:53:00,456 INFO: Found RHSA-2018:0395 (Security - Important) errata. Reboot suggested: Yes.
2018-03-08 13:53:00,456 INFO: Found RHSA-2018:0414 (Security - Important) errata. Reboot suggested: No.
2018-03-08 13:53:00,456 INFO: Found RHSA-2018:0378 (Security - Important) errata. Reboot suggested: No.
2018-03-08 13:53:00,456 INFO: Found RHSA-2018:0377 (Security - Important) errata. Reboot suggested: No.
2018-03-08 13:53:00,456 INFO: Found RHSA-2018:0350 (Security - Important) errata. Reboot suggested: No.
2018-03-08 13:53:00,456 INFO: Found RHSA-2018:0349 (Security - Important) errata. Reboot suggested: No.
2018-03-08 13:53:00,457 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64
2018-03-08 13:53:00,540 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server
2018-03-08 13:53:00,706 INFO: Found RHSA-2018:0406 (Security - Moderate) errata. Reboot suggested: No.
2018-03-08 13:53:00,707 INFO: Found RHSA-2018:0395 (Security - Important) errata. Reboot suggested: Yes.
2018-03-08 13:53:00,707 INFO: Found RHSA-2018:0414 (Security - Important) errata. Reboot suggested: No.
2018-03-08 13:53:00,707 INFO: Found RHSA-2018:0418 (Security - Moderate) errata. Reboot suggested: No.
2018-03-08 13:53:00,707 INFO: Found RHSA-2018:0378 (Security - Important) errata. Reboot suggested: No.
2018-03-08 13:53:00,707 INFO: Found RHSA-2018:0377 (Security - Important) errata. Reboot suggested: No.
2018-03-08 13:53:00,707 INFO: Found RHSA-2018:0350 (Security - Important) errata. Reboot suggested: No.
2018-03-08 13:53:00,707 INFO: Found RHSA-2018:0349 (Security - Important) errata. Reboot suggested: No.
2018-03-08 13:53:00,707 INFO: Searching for erratas in repository Red Hat Enterprise Linux 7 Server - Supplementary RPMs x86_64 7Se        rver
2018-03-08 13:53:00,798 INFO: Found RHSA-2018:0458 (Security - Important) errata. Reboot suggested: No.
2018-03-08 13:53:00,798 INFO: Found RHSA-2018:0351 (Security - Critical) errata. Reboot suggested: No.
2018-03-08 13:53:00,798 INFO: Searching for erratas in repository Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7         Server x86_64 7Server
2018-03-08 13:53:00,875 INFO: Searching for erratas in repository Red Hat Satellite Tools 6.2 for RHEL 7 Server RPMs x86_64
2018-03-08 13:53:00,946 INFO: Selected content-view RHEL7_CV (version 3.0) as baseline to include 10 erratas.
2018-03-08 13:53:00,946 INFO: Publishing incremental content-view version.
Traceback (most recent call last):
  File "./errata2cv.py", line 262, in <module>
    main()
  File "./errata2cv.py", line 212, in main
    while(incremental_update["pending"] != False):
KeyError: 'pending'
```

**Comment by dburrell505** [comment]
Disregard, this is the same issue as before
